version: "3.9"
services:
  app:
    build: .
    image: "operations-engineering-metadata-poc"
    container_name: "operations-engineering-metadata"
    environment:
      FLASK_CONFIGURATION: "development"
      FLASK_DEBUG: "true"
      FLASK_APP: "app"
      DOCKER_COMPOSE_DEV: "true"
    ports:
      - "5000:5000"
