version: "3.9"
services:
  operations-engineering-metadata-db:
    image: postgres:15.0
    container_name: operations-engineering-metadata-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
