apiVersion: v1
kind: Service
metadata:
  name: {{ include "operations-engineering-metadata.fullname" . }}
  labels:
    {{- include "operations-engineering-metadata.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      name: https
  selector:
    {{- include "operations-engineering-metadata.selectorLabels" . | nindent 4 }}
