name: code-formatter

on:
  pull_request:
    paths-ignore:
      - 'helm/**'
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ministryofjustice/github-actions/code-formatter@v14
        with:
          ignore-files: "deployment.yaml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
